// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu3RPIvlyeLGfXL3Q0ku8GXfe5j6vo5p0',
    appId: '1:656800699509:web:69fdf4176c63a565d5943c',
    messagingSenderId: '656800699509',
    projectId: 'todostart-a2ee7',
    authDomain: 'todostart-a2ee7.firebaseapp.com',
    storageBucket: 'todostart-a2ee7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfFZxGFZbxGpgaBywWvosc0gLtVKaH9gA',
    appId: '1:656800699509:android:ef596dd453903dcdd5943c',
    messagingSenderId: '656800699509',
    projectId: 'todostart-a2ee7',
    storageBucket: 'todostart-a2ee7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtSEEoMYm7bEDZMLAxBRqebjthPt7LAwc',
    appId: '1:656800699509:ios:aa98fea9ff4527ecd5943c',
    messagingSenderId: '656800699509',
    projectId: 'todostart-a2ee7',
    storageBucket: 'todostart-a2ee7.appspot.com',
    iosClientId: '656800699509-1fga5q8ngnrpiof9qb4qmjtbh1ct7120.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoPratice',
  );
}
